### PR TITLE
Add xoviat to maintainers

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by xoviat** [comment]
@jakirkham Rather than messing around with merge conflicts, just add me and I'll create the branch.

**Comment by jakirkham** [comment]
So the branch is in the right place. Do you need help fixing conflicts or something?

**Comment by xoviat** [comment]
The branch should be named 'windows' because future versions will be released for the windows branch.

**Comment by xoviat** [comment]
The windows branch should only build windows, and master should only build osx and linux.

**Comment by xoviat** [comment]
@grlee77 If you add me to the maintainers, I assure you that I will not touch the linux/OSX builds.

**Comment by grlee77** [comment]
Okay, I will merge this now, but let's please give it a day or two to try and get some consensus for the windows-specific branch you propose in #30 prior to forging ahead with that approach.  It sounds fine to me, but there are other maintainers here as well who have more conda-forge experience.

**Comment by xoviat** [comment]
I'm not going to merge any PR; what I'm going to do is create the windows branch and then modify the existing PR.

**Pull request merged**
