### PR TITLE
update 5.4.0 (again)

### PR DESCRIPTION
**Pull request by minrk**
- includes #50
- adds newly required m4 build dependency for graphBLAS
- includes patch to exclude demo in mongoose, graphBLAS
- SuiteSparseConfig.mk is patched instead of clobbered, for easier future upgrades

closes #42 
closes #53

### CODE REVIEW

**Comment by minrk** [comment]
Failing with what appears to be a bug in the clang package (or maybe libcxx, I don't know):

Running with `make VERBOSE=1`:

```
[ 27%] Linking CXX executable tests/mongoose_unit_test_edgesep
/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_build_env/bin/cmake -E cmake_link_script CMakeFiles/mongoose_unit_test_edgesep.dir/link.txt --verbose=1
/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_build_env/bin/x86_64-apple-darwin13.4.0-clang++  -O3 -fwrapv -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-pie -Wl,-headerpad_max_install_names  -Wl,-rpath,/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib -L/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib -L/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib --coverage -g CMakeFiles/mongoose_unit_test_edgesep.dir/Tests/Mongoose_UnitTest_EdgeSep_exe.o  -o tests/mongoose_unit_test_edgesep  -L/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/work/Mongoose/../lib -Wl,-rpath,/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/work/Mongoose/../lib lib/libmongoose_dbg.a -lsuitesparseconfig
ld: file not found: /Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_build_env/lib/clang/9.0.0/lib/darwin/libclang_rt.profile_osx.a
```

```
/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_build_env/bin/x86_64-apple-darwin13.4.0-clang++  -O3 -fwrapv -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-pie -Wl,-headerpad_max_install_names  -Wl,-rpath,/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib -L/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib -L/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib --coverage -g CMakeFiles/mongoose_unit_test_edgesep.dir/Tests/Mongoose_UnitTest_EdgeSep_exe.o  -o tests/mongoose_unit_test_edgesep  -L/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/work/Mongoose/../lib -Wl,-rpath,/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/work/Mongoose/../lib lib/libmongoose_dbg.a -lsuitesparseconfig -v
clang version 9.0.0 (tags/RELEASE_900/final)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
InstalledDir: /Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_build_env/bin
 "/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_build_env/bin/x86_64-apple-darwin13.4.0-ld" /Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_build_env/lib/clang/9.0.0/lib/darwin/libclang_rt.profile_osx.a -demangle -lto_library /Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_build_env/lib/libLTO.9.dylib -dynamic -arch x86_64 -macosx_version_min 10.9.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -o tests/mongoose_unit_test_edgesep -L/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib -L/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib -L/Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/work/Mongoose/../lib -search_paths_first -headerpad_max_install_names -pie -headerpad_max_install_names -rpath /Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib CMakeFiles/mongoose_unit_test_edgesep.dir/Tests/Mongoose_UnitTest_EdgeSep_exe.o -rpath /Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/work/Mongoose/../lib lib/libmongoose_dbg.a -lsuitesparseconfig -lc++ -lSystem
ld: file not found: /Users/benjaminrk/conda/conda-bld/suitesparse_1570097153606/_build_env/lib/clang/9.0.0/lib/darwin/libclang_rt.profile_osx.a
```

`/libclang_rt.profile_osx.a` exists, but it is in `_build_env/lib` not `_build_env/lib/clang/9.0.0/lib/darwin`

cc @isuruf

**Comment by minrk** [comment]
Tracked it down to the `--coverage` flag

**Comment by grlee77** [comment]
This looks good to me. Not sure what can be done about the timeout on Travis for ppc64le, though.

**Comment by minrk** [comment]
switched ppc builds to azure, which should hopefully help with running out of time

**Comment by minrk** [comment]
Everything's working here, but ppc64 is timing out because it takes more than six hours to build graphBLAS.

I'd propose merging this as-is and then working on a solution for ppc64, which would be either:

- stop building ppc altogether
- exclude graphBLAS from ppc builds (graphBLAS is new and appears to be entirely disconnected from the rest of suitesparse other than having authors in common)

**Pull request merged**
