### PR TITLE
Use jinja compiler syntax

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by jschueller** [comment]
ping @conda-forge/suitesparse

**Comment by jakirkham** [comment]
LGTM. AFK so will merge when I’m back if no one does before me.

**Comment by jschueller** [comment]
someone from @conda-forge/suitesparse or @conda-forge/core could merge this ?

**Comment by scopatz** [comment]
Please add yourself as a maintainer if you need core to merge into a feedstock. Thanks!

**Pull request merged**
