### PR TITLE
7.7.0

### LINKED ISSUE #79: Static library files should be shipped as a separate output from the shared libraries
### Comment:

Please see our policy regarding not shipping static libraries together with shared libraries.

https://github.com/conda-forge/cfep/blob/main/cfep-18.md

### PR DESCRIPTION
**Pull request by minrk**
- closes #87 
- closes #82 
- closes #79

### CODE REVIEW

**Comment by carterbox** [comment]
Thanks!

**Comment by ManifoldFR** [comment]
Thanks!

**Comment by h-vetinari** [comment]
Nice! Now that we're building with cmake I guess we could also retry native builds for windows.

Originally I had the plan after #82 to split the recipe into more granular outputs, because some places only vendor pieces of suitesparse (for example osqp does IIRC).

**Comment by minrk** [comment]
Yeah, I think we should probably do both of those, too, but figured dedicated PRs after bringing it back to life would put it under a bit less pressure. My guess is Windows will be a lot easier now.

Another question is whether graphblas should be included as a dependency (lagraph is absent because it depends on graphblas). That's easier to require with multiple outputs.

**Pull request merged**
