### PR TITLE
suitesparse 5.7.2 (redux)

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This picks up the fixed patches from @minrk in #61, together with the version bump from #63.

Closes #60 
Closes #61 
Closes #62 
Closes #63

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
The two extant patches have been upstreamed by @minrk in DrTimothyAldenDavis/SuiteSparse#7 & DrTimothyAldenDavis/SuiteSparse#8, so I removed them outright.

**Comment by h-vetinari** [comment]
@conda-forge/suitesparse 
This is green and should allow to close all open PRs. Next step: windows builds. ;-)

**Comment by h-vetinari** [comment]
PS. Link to the [discussion](https://github.com/conda-forge/conda-smithy/pull/1220#issuecomment-612638751) about the conda-smithy warning regarding license identifiers:

**Comment by grlee77** [comment]
Thanks @h-vetinari. Not having the patches should make future automatic updates easier!

**Comment by h-vetinari** [comment]
> @grlee77: Thanks @h-vetinari.

Happy to help. I want to fix the suboptimal cvxopt build (currently building and statically linking suitesparse for windows within that [recipe](https://github.com/conda-forge/cvxopt-feedstock/blob/master/recipe/meta.yaml)), so it made sense to start here. In turn, this also means that cvxopt already knows how to build suitesparse for windows, so I'm hopeful I can leverage that (somehow) into a windows build here (cf. #51).

> Not having the patches should make future automatic updates easier!

All credit for that belongs to @minrk! :)

**Pull request merged**
